### ISSUE TITLE
[Meta] Frontend Refactor

### ISSUE THREAD

**Issue by colescott** [coalton-lang/coalton#316]
This is a meta-issue for the frontend refactor.

As part of the refactor, we should address the following:
- [x] Value passing throughout the frontend is messy and needs to be cleaned up
- [ ] Toplevel forms should be tracked with structures with additional location information
- [x] `define-type` forms need to be topologically sorted
- [x] Environment modifications need to be formalized for each type of toplevel form (see #307)
- [ ] Type parsing and definition parsing is messy and spread across several files
